"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GOODLIST_URL = 'http://rapapi.org/mockjsdata/18396/api/discove/goodlist';
exports.GOODLIST_head_URL = 'http://img.lapin365.com/productpictures';
exports.version = 'V.0.1';
exports.ApiUrl =  'http://119.97.224.22:89/HSApi/api/';
// export ApiUrl = 'http://xiaojieya.picp.io:11352/api';
// exports.ApiUrl = 'http://localhost:1857/api/';
// export const ApiUrl = 'http://10.0.2.2:1857/api/';
export ImgUrl="http://119.97.224.22:89/HSApi/";
